# Generated by Django 3.2.9 on 2021-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='courses',
            field=models.ManyToManyField(to='authentication.Course'),
        ),
    ]
