# Generated by Django 3.2.9 on 2021-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('authentication', '0003_auto_20211208_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
